### ISSUE TITLE
ibmcloud is instance-status <instance id> is not the proper command

### ISSUE THREAD

**Issue by mrappard** [IBM-Bluemix-Docs/vsi-is#12]
ibmcloud is instance-status <instance id> isn't the proper command, it returns

'is' is not a registered command. See 'ibmcloud help'.

**Comment by gudrun-wolfgram** [comment]
Thanks for the good comment. The following topic is updated to use the correct command: _ibmcloud is instance <instance id>_

Connecting to your Windows instance
https://cloud.ibm.com/docs/vsi-is?topic=virtual-servers-is-connecting-to-your-windows-instance
