### ISSUE TITLE
Broken Link: About IBM Cloud VPC

### ISSUE THREAD

**Issue by mperkinson** [IBM-Bluemix-Docs/vsi-is#13]
The 'About IBM Cloud VPC' link under the 'What is IBM Cloud VPC' section of the 'About Virtual Servers for VPC' page is broken. Link: https://cloud.ibm.com/docs/vsi-is?topic=virtual-servers-is-virtual-private-cloud 

When clicking the 'About IBM Cloud VPC' link, I am presented with the following:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/36716743/58179202-b61ecb00-7c75-11e9-8299-78ad4505991a.png">

**Comment by gudrun-wolfgram** [comment]
Link to VPC about page has been updated on About Virtual Servers for VPC' page

https://cloud.ibm.com/docs/vsi-is?topic=virtual-servers-is-virtual-private-cloud
