### ISSUE TITLE
Red Hat Enterprises Linux is missing from 'Stock Images' list

### ISSUE THREAD

**Issue by mperkinson** [IBM-Bluemix-Docs/vsi-is#14]
Red Hat Enterprise Linux 7.x is an available OS image for VSIs. This OS is missing from the 'Stock Images' list. Link: https://cloud.ibm.com/docs/vsi-is?topic=virtual-servers-is-images

Please see below for a screenshot of available images from the portal. Note the Red Hat Enterprise Linux option.

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/36716743/58182459-a4402680-7c7b-11e9-9eca-af2cd1fdd560.png">

**Comment by gudrun-wolfgram** [comment]
Thanks for the comment. The topic is updated to include RHEL. 

https://cloud.ibm.com/docs/vsi-is?topic=virtual-servers-is-images
