### ISSUE TITLE
User Data description not sufficient

### ISSUE THREAD

**Issue by powellquiring** [IBM-Bluemix-Docs/vsi-is#4]
https://console.bluemix.net/docs/vsi-is/vsi_is_provisioning_scripts.html#user-data

there are two text boxes:

#cloud-config
users:
  - name: demouser
    gecos: Demo User
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    ssh_import_id: None
    lock_passwd: true
    ssh_authorized_keys:
        - <ssh public key>

- - - - -

#!/bin/bash
echo <sshKey> > ~/.ssh/authorized_keys

- - - - -
 I don't understand what my next step is.  Should I copy and paste the contents of both these boxes into the User Data text box?

![image](https://user-images.githubusercontent.com/6932057/43742071-6fac9c0c-9985-11e8-9b24-fc153cf4910f.png)

**Comment by mlgordon** [comment]
@powellquiring Thank you for this feedback. I will do some investigating and make this more clear!

**Comment by gudrun-wolfgram** [comment]
@powellquiring - I just submitted an update to clarify that only one of the examples needs to be pasted into the User Data text box. The change should be available when the build completes. Thanks!
